# Generated by Django 5.2.10 on 2026-01-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_user_type_favoritesubjects_starredmember'),
        ('notifications', '0002_alter_device_options_device_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starredbill',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='starredbill',
            unique_together={('user_profile', 'bill_id')},
        ),
        migrations.RemoveField(
            model_name='starredbill',
            name='device',
        ),
    ]
