# Generated by Django 5.2.10 on 2026-01-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_starredmember_unique_together_and_more'),
        ('notifications', '0003_alter_starredbill_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starredbill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='starredbill',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starred_bills', to='app.userprofile'),
        ),
        migrations.CreateModel(
            name='FavoriteSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_subjects', to='app.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='StarredMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_memberships', to='app.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'membership_id')},
            },
        ),
    ]
