# Generated by Django 5.2.10 on 2026-02-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_starredmember_unique_together_and_more'),
        ('notifications', '0004_starredbill_is_active_alter_starredbill_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app.userprofile'),
        ),
    ]
