# Generated by Django 4.2.7 on 2024-12-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SenateQuery', '0003_member_first_name_member_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('issue', models.CharField(blank=True, max_length=10, null=True)),
                ('dateTime', models.DateTimeField()),
                ('question', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('result', models.CharField(max_length=10)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.congress')),
                ('nays', models.ManyToManyField(related_name='nays', to='SenateQuery.membership')),
                ('novt', models.ManyToManyField(related_name='novt', to='SenateQuery.membership')),
                ('pres', models.ManyToManyField(related_name='pres', to='SenateQuery.membership')),
                ('yeas', models.ManyToManyField(related_name='yeas', to='SenateQuery.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceVote',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('issue', models.CharField(blank=True, max_length=10, null=True)),
                ('dateTime', models.DateTimeField()),
                ('question', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('result', models.CharField(max_length=40)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.congress')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=40)),
                ('choice_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillQuery.choicevote')),
                ('supporters', models.ManyToManyField(to='SenateQuery.membership')),
            ],
        ),
    ]
