# Generated by Django 4.2.7 on 2025-01-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SenateQuery', '0005_member_death_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('origin_date', models.DateField()),
                ('latest_action', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('question', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('result', models.CharField(max_length=20)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill')),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.congress')),
                ('nays', models.ManyToManyField(related_name='nays', to='SenateQuery.membership')),
                ('novt', models.ManyToManyField(related_name='novt', to='SenateQuery.membership')),
                ('pres', models.ManyToManyField(related_name='pres', to='SenateQuery.membership')),
                ('yeas', models.ManyToManyField(related_name='yeas', to='SenateQuery.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceVote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('question', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('result', models.CharField(max_length=40)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill')),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.congress')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=40)),
                ('choice_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillQuery.choicevote')),
                ('supporters', models.ManyToManyField(to='SenateQuery.membership')),
            ],
        ),
    ]
