# Generated by Django 4.2.7 on 2025-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
