# Generated by Django 4.2.7 on 2024-12-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0002_alter_vote_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choicevote',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='issue',
        ),
        migrations.AlterField(
            model_name='choicevote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='choicevote',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill'),
        ),
        migrations.AddField(
            model_name='vote',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill'),
        ),
    ]
