# Generated by Django 4.2.7 on 2025-01-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0002_alter_bill_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['origin_date']},
        ),
    ]
