# Generated by Django 4.2.7 on 2025-01-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0003_alter_bill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['origin_date', 'latest_action']},
        ),
        migrations.AlterModelOptions(
            name='choicevote',
            options={'ordering': ['dateTime']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['dateTime']},
        ),
    ]
