# Generated by Django 4.2.7 on 2025-01-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0005_member_death_year'),
        ('BillQuery', '0005_alter_bill_options_alter_choicevote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='nays',
            field=models.ManyToManyField(blank=True, related_name='nays', to='SenateQuery.membership'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='novt',
            field=models.ManyToManyField(blank=True, related_name='novt', to='SenateQuery.membership'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='pres',
            field=models.ManyToManyField(blank=True, related_name='pres', to='SenateQuery.membership'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='yeas',
            field=models.ManyToManyField(blank=True, related_name='yeas', to='SenateQuery.membership'),
        ),
    ]
