# Generated by Django 4.2.7 on 2025-01-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0006_alter_vote_nays_alter_vote_novt_alter_vote_pres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
