# Generated by Django 4.2.7 on 2025-02-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0007_alter_vote_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='house',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
