# Generated by Django 4.2.7 on 2025-02-12 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0008_remove_membership_leadership_membership_geoid'),
        ('BillQuery', '0010_alter_bill_options_alter_vote_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.membership'),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
