# Generated by Django 4.2.7 on 2025-02-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0009_remove_member_api_url_remove_membership_chamber_and_more'),
        ('BillQuery', '0011_bill_sponsor_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.membership'),
        ),
        migrations.AlterField(
            model_name='choicevote',
            name='bill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill'),
        ),
        migrations.AlterField(
            model_name='choicevote',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vote',
            name='bill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='house',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
