# Generated by Django 4.2.20 on 2025-04-11 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0012_alter_bill_sponsor_alter_choicevote_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('summary', models.TextField(default='We cannot provide a summary at this time.')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-latest_action', 'origin_date', '-id']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vote',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillQuery.bill'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
