# Generated by Django 4.2.7 on 2025-05-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0013_added_BillSummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPrediction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BinaryProbability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('in_house', models.BooleanField(default=True)),
                ('party', models.CharField(max_length=30)),
                ('counts', models.IntegerField()),
                ('p', models.DecimalField(decimal_places=5, max_digits=5)),
                ('bill_pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillQuery.billprediction')),
            ],
        ),
    ]
