# Generated by Django 4.2.7 on 2025-07-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0011_added_BillSummary'),
        ('BillQuery', '0015_alter_vote_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='cosponsors',
            field=models.ManyToManyField(related_name='cosponsor_set', to='SenateQuery.membership'),
        ),
        migrations.AddField(
            model_name='bill',
            name='policy_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='subjects',
            field=models.ManyToManyField(to='BillQuery.subject'),
        ),
    ]
