# Generated by Django 4.2.7 on 2025-07-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0016_subject_bill_cosponsors_bill_policy_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='related_bills',
            field=models.ManyToManyField(to='BillQuery.bill'),
        ),
    ]
