# Generated by Django 4.2.7 on 2025-07-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0017_bill_related_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
