# Generated by Django 4.2.7 on 2025-07-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0019_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='latest_db_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
