# Generated by Django 4.2.7 on 2025-07-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0020_bill_latest_db_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subtype',
            field=models.IntegerField(default=0),
        ),
    ]
