# Generated by Django 5.2.5 on 2025-08-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0021_subject_subtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
