# Generated by Django 5.2.8 on 2025-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0022_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='latest_action',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='origin_date',
            field=models.DateField(db_index=True),
        ),
    ]
