# Generated by Django 5.2.9 on 2026-01-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0023_alter_bill_latest_action_alter_bill_origin_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-dateTime', '-id']},
        ),
    ]
