# Generated by Django 5.2.10 on 2026-02-13 19:22

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0024_alter_vote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
