# Generated by Django 5.2.10 on 2026-02-13 19:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0025_bill_search_vector'),
        ('SenateQuery', '0011_added_BillSummary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='BillQuery_b_search__23023b_gin'),
        ),
    ]
