# Generated by Django 5.2.10 on 2026-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0026_bill_billquery_b_search__23023b_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
    ]
