# Generated by Django 5.2.13 on 2026-05-01 21:07
# Jerm added sql updating existing rows on 2026-05-01 21:09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0027_bill_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status_code',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.RunSQL(
            sql='UPDATE "BillQuery_bill" SET "status_code" = -1 WHERE "status_code" = 0',
            reverse_sql='UPDATE "BillQuery_bill" SET "status_code" = 0 WHERE "status_code" = -1'
        ),


    ]
