# Generated by Django 5.2.13 on 2026-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillQuery', '0028_alter_bill_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='conf_in_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='veto_in_history',
            field=models.BooleanField(default=False),
        ),
    ]
