import json
import datetime
import re
import ast
import aiohttp
from bs4 import BeautifulSoup
from USQuery import settings
from SenateQuery.models import Membership
from app import utils
import pandas as pd
import tensorflow as tf
from google.genai import types
from google import genai

prompt = """Given this bill text and the list of subjects, create a python 
    dictionary where the keys are the subjects and the value is an integer 
    score from -20 to 20 where 20 means the bill is very progressive in 
    this subject and -20 means the bill is very conservative. Make sure to 
    only include subjects that exist in the provided list, and make sure 
    the values are only the score from -20 to 20. The return should be a 
    literal python dictionary.
"""
subject_dict = {
	'house': 0,
	'party_Democratic': 1,
	'party_Independent': 2,
	'party_Libertarian': 3,
	'party_Republican': 4,
	'Abortion': 5,
	'Academic performance and assessments': 6,
	'Accidents': 7,
	'Accounting and auditing': 8,
	'Administrative law and regulatory procedures': 9,
	'Administrative remedies': 10,
	'Adoption and foster care': 11,
	'Adult day care': 12,
	'Adult education and literacy': 13,
	'Advanced technology and technological innovations': 14,
	'Advisory bodies': 15,
	'Age discrimination': 16,
	'Aging': 17,
	'Agricultural conservation and pollution': 18,
	'Agricultural education': 19,
	'Agricultural equipment and machinery': 20,
	'Agricultural insurance': 21,
	'Agricultural marketing and promotion': 22,
	'Agricultural practices and innovations': 23,
	'Agricultural prices, subsidies, credit': 24,
	'Agricultural research': 25,
	'Agricultural trade': 26,
	'Air quality': 27,
	'Alaska Natives and Hawaiians': 28,
	'Alcoholic beverages': 29,
	'Allergies': 30,
	'Alliances': 31,
	'Allied health services': 32,
	'Alternative and renewable resources': 33,
	'Alternative dispute resolution, mediation, arbitration': 34,
	'Alternative treatments': 35,
	'Animal and plant health': 36,
	'Animal protection and human-animal relationships': 37,
	'Appropriations': 38,
	'Aquaculture': 39,
	'Aquatic ecology': 40,
	'Arab-Israeli relations': 41,
	'Archaeology and anthropology': 42,
	'Architecture': 43,
	'Arctic and polar regions': 44,
	'Area studies and international education': 45,
	'Arms control and nonproliferation': 46,
	'Art, artists, authorship': 47,
	'Assault and harassment offenses': 48,
	'Astronomy': 49,
	'Athletes': 50,
	'Atmospheric science and weather': 51,
	'Aviation and airports': 52,
	'Bank accounts, deposits, capital': 53,
	'Banking and financial institutions regulation': 54,
	'Bankruptcy': 55,
	'Behavioral sciences': 56,
	'Biological and life sciences': 57,
	'Birds': 58,
	'Birth defects': 59,
	'Blood and blood diseases': 60,
	'Books and print media': 61,
	'Border security and unlawful immigration': 62,
	'Broadcasting, cable, digital technologies': 63,
	'Budget deficits and national debt': 64,
	'Budget process': 65,
	'Building construction': 66,
	'Business education': 67,
	'Business ethics': 68,
	'Business expenses': 69,
	'Business investment and capital': 70,
	'Business records': 71,
	'Buy American requirements': 72,
	'Cancer': 73,
	'Capital gains tax': 74,
	'Cardiovascular and respiratory health': 75,
	'Cell biology and embryology': 76,
	'Cemeteries and funerals': 77,
	'Census and government statistics': 78,
	'Charitable contributions': 79,
	'Chemical and biological weapons': 80,
	'Chemistry': 81,
	'Child care and development': 82,
	'Child health': 83,
	'Child safety and welfare': 84,
	'Citizenship and naturalization': 85,
	'Civics education': 86,
	'Civil actions and liability': 87,
	'Civil disturbances': 88,
	'Climate change and greenhouse gases': 89,
	'Coal': 90,
	'Coast guard': 91,
	'Collective security': 92,
	'Commemorative events and holidays': 93,
	'Commodities markets': 94,
	'Community life and organization': 95,
	'Commuting': 96,
	'Competition and antitrust': 97,
	'Competitiveness, trade promotion, trade deficits': 98,
	'Comprehensive health care': 99,
	'Computer security and identity theft': 100,
	'Computers and information technology': 101,
	'Conflicts and wars': 102,
	'Congressional agencies': 103,
	'Congressional committees': 104,
	'Congressional districts and representation': 105,
	'Congressional elections': 106,
	'Congressional leadership': 107,
	'Congressional officers and employees': 108,
	'Congressional operations and organization': 109,
	'Congressional oversight': 110,
	'Congressional tributes': 111,
	'Congressional-executive branch relations': 112,
	'Constitution and constitutional amendments': 113,
	'Consumer affairs': 114,
	'Consumer credit': 115,
	'Contracts and agency': 116,
	'Cooperative and condominium housing': 117,
	'Corporate finance and management': 118,
	'Correctional facilities and imprisonment': 119,
	'Cosmetics and personal care': 120,
	'Credit and credit markets': 121,
	'Crime prevention': 122,
	'Crime victims': 123,
	'Crimes against animals and natural resources': 124,
	'Crimes against children': 125,
	'Crimes against property': 126,
	'Crimes against women': 127,
	'Criminal investigation, prosecution, interrogation': 128,
	'Criminal justice information and records': 129,
	'Criminal procedure and sentencing': 130,
	'Cultural exchanges and relations': 131,
	'Currency': 132,
	'Customs enforcement': 133,
	'Dams and canals': 134,
	'Debt collection': 135,
	'Defense spending': 136,
	'Dental care': 137,
	'Detention of persons': 138,
	'Digestive and metabolic diseases': 139,
	'Digital media': 140,
	'Diplomacy, foreign officials, Americans abroad': 141,
	'Disability and health-based discrimination': 142,
	'Disability and paralysis': 143,
	'Disability assistance': 144,
	'Disaster relief and insurance': 145,
	'Domestic violence and child abuse': 146,
	'Drug safety, medical device, and laboratory regulation': 147,
	'Drug therapy': 148,
	'Drug trafficking and controlled substances': 149,
	'Drug, alcohol, tobacco use': 150,
	'Due process and equal protection': 151,
	'Earth sciences': 152,
	'Ecology': 153,
	'Economic development': 154,
	'Economic performance and conditions': 155,
	'Economic theory': 156,
	'Education of the disadvantaged': 157,
	'Education programs funding': 158,
	'Educational facilities and institutions': 159,
	'Educational guidance': 160,
	'Educational technology and distance education': 161,
	'Elections, voting, political campaign regulation': 162,
	'Electric power generation and transmission': 163,
	'Elementary and secondary education': 164,
	'Emergency communications systems': 165,
	'Emergency medical services and trauma care': 166,
	'Emergency planning and evacuation': 167,
	'Employee benefits and pensions': 168,
	'Employee hiring': 169,
	'Employee leave': 170,
	'Employee performance': 171,
	'Employment and training programs': 172,
	'Employment discrimination and employee rights': 173,
	'Employment taxes': 174,
	'Endangered and threatened species': 175,
	'Energy assistance for the poor and aged': 176,
	'Energy efficiency and conservation': 177,
	'Energy prices': 178,
	'Energy research': 179,
	'Energy revenues and royalties': 180,
	'Energy storage, supplies, demand': 181,
	'Environmental assessment, monitoring, research': 182,
	'Environmental education': 183,
	'Environmental health': 184,
	'Environmental regulatory procedures': 185,
	'Environmental technology': 186,
	'Espionage and treason': 187,
	'Ethnic studies': 188,
	'Evidence and witnesses': 189,
	'Executive agency funding and structure': 190,
	'Family planning and birth control': 191,
	'Family relationships': 192,
	'Family services': 193,
	'Farmland': 194,
	'Federal appellate courts': 195,
	'Federal district courts': 196,
	'Federal officials': 197,
	'Federal preemption': 198,
	'Federal-Indian relations': 199,
	'Federally chartered organizations': 200,
	'Financial crises and stabilization': 201,
	'Financial literacy': 202,
	'Financial services and investments': 203,
	'Firearms and explosives': 204,
	'Fires': 205,
	'First Amendment rights': 206,
	'First responders and emergency personnel': 207,
	'Fishes': 208,
	'Floods and storm protection': 209,
	'Food assistance and relief': 210,
	'Food industry and services': 211,
	'Food supply, safety, and labeling': 212,
	'Foreign aid and international relief': 213,
	'Foreign and international banking': 214,
	'Foreign and international corporations': 215,
	'Foreign labor': 216,
	'Foreign language and bilingual programs': 217,
	'Foreign loans and debt': 218,
	'Foreign property': 219,
	'Forests, forestry, trees': 220,
	'Fraud offenses and financial crimes': 221,
	'Free trade and trade barriers': 222,
	'Freedom of information': 223,
	'Fruit and vegetables': 224,
	'Gambling': 225,
	'Games and hobbies': 226,
	'General Native American affairs matters': 227,
	'General agriculture matters': 228,
	'General business and commerce matters': 229,
	'General education matters': 230,
	'General energy matters': 231,
	'General foreign operations matters': 232,
	'General health and health care finance matters': 233,
	'General public lands matters': 234,
	'General science and technology matters': 235,
	'General taxation matters': 236,
	'Genetics': 237,
	'Geography and mapping': 238,
	'Government buildings, facilities, and property': 239,
	'Government corporations and government-sponsored enterprises': 240,
	'Government employee pay, benefits, personnel management': 241,
	'Government ethics and transparency, public corruption': 242,
	'Government information and archives': 243,
	'Government lending and loan guarantees': 244,
	'Government liability': 245,
	'Government studies and investigations': 246,
	'Government trust funds': 247,
	'Grain': 248,
	'HIV/AIDS': 249,
	'Hate crimes': 250,
	'Hazardous wastes and toxic substances': 251,
	'Health care costs and insurance': 252,
	'Health care coverage and access': 253,
	'Health care quality': 254,
	'Health facilities and institutions': 255,
	'Health information and medical records': 256,
	'Health personnel': 257,
	'Health programs administration and funding': 258,
	'Health promotion and preventive care': 259,
	'Health technology, devices, supplies': 260,
	'Hearing, speech, and vision care': 261,
	'Hereditary and development disorders': 262,
	'Higher education': 263,
	'Historic sites and heritage areas': 264,
	'Historical and cultural resources': 265,
	'Home and outpatient care': 266,
	'Homeland security': 267,
	'Homelessness and emergency shelter': 268,
	'Horticulture and plants': 269,
	'Hospital care': 270,
	'House of Representatives': 271,
	'Housing and community development funding': 272,
	'Housing discrimination': 273,
	'Housing finance and home ownership': 274,
	'Housing for the elderly and disabled': 275,
	'Housing industry and standards': 276,
	'Housing supply and affordability': 277,
	'Human rights': 278,
	'Human trafficking': 279,
	'Humanities programs funding': 280,
	'Hunting and fishing': 281,
	'Hybrid, electric, and advanced technology vehicles': 282,
	'Hydrology and hydrography': 283,
	'Immigrant health and welfare': 284,
	'Immigration status and procedures': 285,
	'Immunology and vaccination': 286,
	'Income tax credits': 287,
	'Income tax deductions': 288,
	'Income tax deferral': 289,
	'Income tax exclusion': 290,
	'Income tax rates': 291,
	'Indian claims': 292,
	'Indian lands and resources rights': 293,
	'Indian social and development programs': 294,
	'Industrial facilities': 295,
	'Industrial policy and productivity': 296,
	'Infectious and parasitic diseases': 297,
	'Inflation and prices': 298,
	'Infrastructure development': 299,
	'Insects': 300,
	'Insurance industry and regulation': 301,
	'Intellectual property': 302,
	'Intelligence activities, surveillance, classified information': 303,
	'Interest, dividends, interest rates': 304,
	'Intergovernmental relations': 305,
	'International exchange and broadcasting': 306,
	'International law and treaties': 307,
	'International monetary system and foreign exchange': 308,
	'International organizations and cooperation': 309,
	'International scientific cooperation': 310,
	'Internet, web applications, social media': 311,
	'Judges': 312,
	'Judicial procedure and administration': 313,
	'Judicial review and appeals': 314,
	'Jurisdiction and venue': 315,
	'Juvenile crime and gang violence': 316,
	'Labor market': 317,
	'Labor standards': 318,
	'Labor-management relations': 319,
	'Lakes and rivers': 320,
	'Land transfers': 321,
	'Land use and conservation': 322,
	'Landlord and tenant': 323,
	'Language arts': 324,
	'Law enforcement administration and funding': 325,
	'Law enforcement officers': 326,
	'Lawyers and legal services': 327,
	'Lease and rental services': 328,
	'Legal fees and court costs': 329,
	'Legislative rules and procedure': 330,
	'Libraries and archives': 331,
	'Licensing and registrations': 332,
	'Life, casualty, property insurance': 333,
	'Lighting, heating, cooling': 334,
	'Literature': 335,
	'Livestock': 336,
	'Long-term, rehabilitative, and terminal care': 337,
	'Low- and moderate-income housing': 338,
	'Mammals': 339,
	'Manufacturing': 340,
	'Marine and coastal resources, fisheries': 341,
	'Marine and inland water transportation': 342,
	'Marine pollution': 343,
	'Marketing and advertising': 344,
	'Marriage and family status': 345,
	'Materials': 346,
	'Meat': 347,
	'Medicaid': 348,
	'Medical education': 349,
	'Medical ethics': 350,
	'Medical research': 351,
	'Medical tests and diagnostic methods': 352,
	'Medicare': 353,
	'Members of Congress': 354,
	'Mental health': 355,
	'Metals': 356,
	'Migrant, seasonal, agricultural labor': 357,
	'Military assistance, sales, and agreements': 358,
	'Military civil functions': 359,
	'Military command and structure': 360,
	'Military education and training': 361,
	'Military facilities and property': 362,
	'Military history': 363,
	'Military law': 364,
	'Military medicine': 365,
	'Military operations and strategy': 366,
	'Military personnel and dependents': 367,
	'Military procurement, research, weapons development': 368,
	'Military readiness': 369,
	'Militias and paramilitary groups': 370,
	'Mining': 371,
	'Minority and disadvantaged businesses': 372,
	'Minority education': 373,
	'Minority employment': 374,
	'Minority health': 375,
	'Missing persons': 376,
	'Monetary policy': 377,
	'Monuments and memorials': 378,
	'Motor carriers': 379,
	'Motor fuels': 380,
	'Motor vehicles': 381,
	'Multilateral development programs': 382,
	'Musculoskeletal and skin diseases': 383,
	'Museums, exhibitions, cultural centers': 384,
	'Music': 385,
	'National Guard and reserves': 386,
	'National and community service': 387,
	'National symbols': 388,
	'Natural disasters': 389,
	'Navigation, waterways, harbors': 390,
	'Neurological disorders': 391,
	'News media and reporting': 392,
	'Noise pollution': 393,
	'Normal trade relations, most-favored-nation treatment': 394,
	'Nuclear power': 395,
	'Nuclear weapons': 396,
	'Nursing': 397,
	'Nutrition and diet': 398,
	'Oil and gas': 399,
	'Olympic games': 400,
	'Organ and tissue donation and transplantation': 401,
	'Organized crime': 402,
	'Outdoor recreation': 403,
	'Palestinians': 404,
	'Parks, recreation areas, trails': 405,
	'Pedestrians and bicycling': 406,
	'Performance measurement': 407,
	'Performing arts': 408,
	'Personnel records': 409,
	'Pest management': 410,
	'Photography and imaging': 411,
	'Physical fitness and lifestyle': 412,
	'Pipelines': 413,
	'Policy sciences': 414,
	'Political advertising': 415,
	'Political movements and philosophies': 416,
	'Political parties and affiliation': 417,
	'Political representation': 418,
	'Pollution liability': 419,
	'Pornography': 420,
	'Postal service': 421,
	'Poverty and welfare assistance': 422,
	'Preschool education': 423,
	'Prescription drugs': 424,
	'Presidential administrations': 425,
	'Presidents and presidential powers, Vice Presidents': 426,
	'Private Legislation': 427,
	'Product development and innovation': 428,
	'Product safety and quality': 429,
	'Professional sports': 430,
	'Property rights': 431,
	'Property tax': 432,
	'Protection of officials': 433,
	'Protest and dissent': 434,
	'Public contracts and procurement': 435,
	'Public housing': 436,
	'Public participation and lobbying': 437,
	'Public transit': 438,
	'Public utilities and utility rates': 439,
	'Public-private cooperation': 440,
	'Racial and ethnic relations': 441,
	'Radiation': 442,
	'Radio spectrum allocation': 443,
	'Radioactive wastes and releases': 444,
	'Railroads': 445,
	'Real estate business': 446,
	'Reconstruction and stabilization': 447,
	'Refugees, asylum, displaced persons': 448,
	'Regional and metropolitan planning': 449,
	'Religion': 450,
	'Reptiles': 451,
	'Research administration and funding': 452,
	'Research and development': 453,
	'Research ethics': 454,
	'Residential rehabilitation and home repair': 455,
	'Retail and wholesale trades': 456,
	'Right of privacy': 457,
	'Roads and highways': 458,
	'Rule of law and government transparency': 459,
	'Rural conditions and development': 460,
	'Sales and excise taxes': 461,
	'Sanctions': 462,
	'School administration': 463,
	'School athletics': 464,
	'Science and engineering education': 465,
	'Scientific communication': 466,
	'Seafood': 467,
	'Seashores and lakeshores': 468,
	'Securities': 469,
	'Self-employed': 470,
	'Senate': 471,
	'Separation, divorce, custody, support': 472,
	'Service animals': 473,
	'Service industries': 474,
	'Sex and reproductive health': 475,
	'Sex offenses': 476,
	'Sex, gender, sexual orientation discrimination': 477,
	'Sexually transmitted diseases': 478,
	'Small business': 479,
	'Small towns': 480,
	'Smuggling and trafficking': 481,
	'Social security and elderly assistance': 482,
	'Social work, volunteer service, charitable organizations': 483,
	'Soil pollution': 484,
	'Solid waste and recycling': 485,
	'Sound recording': 486,
	'Sovereignty, recognition, national governance and status': 487,
	'Space flight and exploration': 488,
	'Spacecraft and satellites': 489,
	'Special education': 490,
	'Specialized courts': 491,
	'Sports and recreation facilities': 492,
	'State and local courts': 493,
	'State and local finance': 494,
	'State and local government operations': 495,
	'State and local taxation': 496,
	'Strategic materials and reserves': 497,
	'Student aid and college costs': 498,
	'Student records': 499,
	'Subversive activities': 500,
	'Supreme Court': 501,
	'Surgery and anesthesia': 502,
	'Tariffs': 503,
	'Tax administration and collection, taxpayers': 504,
	'Tax reform and tax simplification': 505,
	'Tax treatment of families': 506,
	'Tax-exempt organizations': 507,
	'Taxation of foreign income': 508,
	'Teaching, teachers, curricula': 509,
	'Technology assessment': 510,
	'Technology transfer and commercialization': 511,
	'Teenage pregnancy': 512,
	'Telecommunication rates and fees': 513,
	'Telephone and wireless communication': 514,
	'Television and film': 515,
	'Temporary and part-time employment': 516,
	'Terrorism': 517,
	'Time and calendar': 518,
	'Trade adjustment assistance': 519,
	'Trade agreements and negotiations': 520,
	'Trade restrictions': 521,
	'Trade secrets and economic espionage': 522,
	'Transfer and inheritance taxes': 523,
	'Transportation costs': 524,
	'Transportation employees': 525,
	'Transportation programs funding': 526,
	'Transportation safety and security': 527,
	'Travel and tourism': 528,
	'U.S. Capitol': 529,
	'U.S. and foreign investments': 530,
	'U.S. history': 531,
	'U.S. territories and protectorates': 532,
	'Unemployment': 533,
	'Urban and suburban affairs and development': 534,
	'User charges and fees': 535,
	"Veterans' education, employment, rehabilitation": 536,
	"Veterans' loans, housing, homeless programs": 537,
	"Veterans' medical care": 538,
	"Veterans' organizations and recognition": 539,
	"Veterans' pensions and compensation": 540,
	'Veterinary medicine and animal diseases': 541,
	'Violent crime': 542,
	'Visas and passports': 543,
	'Vocational and technical education': 544,
	'Voting rights': 545,
	'Wages and earnings': 546,
	'War and emergency powers': 547,
	'War crimes, genocide, crimes against humanity': 548,
	'Water quality': 549,
	'Water resources funding': 550,
	'Water storage': 551,
	'Water use and supply': 552,
	'Watersheds': 553,
	'Wetlands': 554,
	'White-collar crime': 555,
	'Wilderness and natural areas, wildlife refuges, wild rivers, habitats': 556,
	'Wildlife conservation and habitat protection': 557,
	'Women in business': 558,
	"Women's education": 559,
	"Women's employment": 560,
	"Women's health": 561,
	"Women's rights": 562,
	'Worker safety and health': 563,
	'World health': 564,
	'World history': 565,
	'Youth employment and child labor': 566
}

feature_list = ['house', 'party_Democratic', 'party_Independent', 'party_Libertarian', 'party_Republican',
	'Abortion', 'Academic performance and assessments', 'Accidents', 'Accounting and auditing',
	'Administrative law and regulatory procedures', 'Administrative remedies', 'Adoption and foster care',
	'Adult day care', 'Adult education and literacy', 'Advanced technology and technological innovations',
	'Advisory bodies', 'Age discrimination', 'Aging', 'Agricultural conservation and pollution',
	'Agricultural education', 'Agricultural equipment and machinery', 'Agricultural insurance',
	'Agricultural marketing and promotion', 'Agricultural practices and innovations', 
	'Agricultural prices, subsidies, credit', 'Agricultural research', 'Agricultural trade', 'Air quality',
    'Alaska Natives and Hawaiians', 'Alcoholic beverages', 'Allergies', 'Alliances', 'Allied health services',
    'Alternative and renewable resources', 'Alternative dispute resolution, mediation, arbitration',
    'Alternative treatments', 'Animal and plant health', 'Animal protection and human-animal relationships',
    'Appropriations', 'Aquaculture', 'Aquatic ecology', 'Arab-Israeli relations', 'Archaeology and anthropology',
    'Architecture', 'Arctic and polar regions', 'Area studies and international education',
    'Arms control and nonproliferation', 'Art, artists, authorship', 'Assault and harassment offenses',
    'Astronomy', 'Athletes', 'Atmospheric science and weather', 'Aviation and airports',
    'Bank accounts, deposits, capital', 'Banking and financial institutions regulation', 'Bankruptcy',
    'Behavioral sciences', 'Biological and life sciences', 'Birds', 'Birth defects', 'Blood and blood diseases',
    'Books and print media', 'Border security and unlawful immigration', 'Broadcasting, cable, digital technologies',
    'Budget deficits and national debt', 'Budget process', 'Building construction', 'Business education',
    'Business ethics', 'Business expenses', 'Business investment and capital', 'Business records',
    'Buy American requirements', 'Cancer', 'Capital gains tax', 'Cardiovascular and respiratory health',
    'Cell biology and embryology', 'Cemeteries and funerals', 'Census and government statistics', 'Charitable contributions',
    'Chemical and biological weapons', 'Chemistry', 'Child care and development', 'Child health', 'Child safety and welfare',
    'Citizenship and naturalization', 'Civics education', 'Civil actions and liability', 'Civil disturbances',
    'Climate change and greenhouse gases', 'Coal', 'Coast guard', 'Collective security', 'Commemorative events and holidays',
    'Commodities markets', 'Community life and organization', 'Commuting', 'Competition and antitrust',
    'Competitiveness, trade promotion, trade deficits', 'Comprehensive health care', 'Computer security and identity theft',
    'Computers and information technology', 'Conflicts and wars', 'Congressional agencies', 'Congressional committees',
    'Congressional districts and representation', 'Congressional elections', 'Congressional leadership',
    'Congressional officers and employees', 'Congressional operations and organization', 'Congressional oversight',
    'Congressional tributes', 'Congressional-executive branch relations', 'Constitution and constitutional amendments',
    'Consumer affairs', 'Consumer credit', 'Contracts and agency', 'Cooperative and condominium housing',
    'Corporate finance and management', 'Correctional facilities and imprisonment', 'Cosmetics and personal care',
    'Credit and credit markets', 'Crime prevention', 'Crime victims', 'Crimes against animals and natural resources',
    'Crimes against children', 'Crimes against property', 'Crimes against women',
    'Criminal investigation, prosecution, interrogation', 'Criminal justice information and records',
    'Criminal procedure and sentencing', 'Cultural exchanges and relations', 'Currency', 'Customs enforcement', 
	'Dams and canals', 'Debt collection', 'Defense spending', 'Dental care', 'Detention of persons', 
	'Digestive and metabolic diseases', 'Digital media', 'Diplomacy, foreign officials, Americans abroad', 
	'Disability and health-based discrimination', 'Disability and paralysis', 'Disability assistance', 
	'Disaster relief and insurance', 'Domestic violence and child abuse', 
	'Drug safety, medical device, and laboratory regulation', 'Drug therapy', 'Drug trafficking and controlled substances', 
	'Drug, alcohol, tobacco use', 'Due process and equal protection', 'Earth sciences', 'Ecology', 'Economic development', 
	'Economic performance and conditions', 'Economic theory', 'Education of the disadvantaged', 'Education programs funding', 
	'Educational facilities and institutions', 'Educational guidance', 'Educational technology and distance education', 
	'Elections, voting, political campaign regulation', 'Electric power generation and transmission', 
	'Elementary and secondary education', 'Emergency communications systems', 'Emergency medical services and trauma care',
	'Emergency planning and evacuation', 'Employee benefits and pensions', 'Employee hiring', 'Employee leave',
	'Employee performance', 'Employment and training programs', 'Employment discrimination and employee rights',
	'Employment taxes', 'Endangered and threatened species', 'Energy assistance for the poor and aged', 
	'Energy efficiency and conservation', 'Energy prices', 'Energy research', 'Energy revenues and royalties', 
	'Energy storage, supplies, demand', 'Environmental assessment, monitoring, research', 'Environmental education', 
	'Environmental health', 'Environmental regulatory procedures', 'Environmental technology', 'Espionage and treason', 
	'Ethnic studies', 'Evidence and witnesses', 'Executive agency funding and structure', 'Family planning and birth control', 
	'Family relationships', 'Family services', 'Farmland', 'Federal appellate courts', 'Federal district courts', 
	'Federal officials', 'Federal preemption', 'Federal-Indian relations', 'Federally chartered organizations', 
	'Financial crises and stabilization', 'Financial literacy', 'Financial services and investments', 'Firearms and explosives', 
	'Fires', 'First Amendment rights', 'First responders and emergency personnel', 'Fishes', 'Floods and storm protection', 
	'Food assistance and relief', 'Food industry and services', 'Food supply, safety, and labeling', 
	'Foreign aid and international relief', 'Foreign and international banking', 'Foreign and international corporations', 
	'Foreign labor', 'Foreign language and bilingual programs', 'Foreign loans and debt', 'Foreign property', 
	'Forests, forestry, trees', 'Fraud offenses and financial crimes', 'Free trade and trade barriers', 'Freedom of information', 
	'Fruit and vegetables', 'Gambling', 'Games and hobbies', 'General Native American affairs matters', 
	'General agriculture matters', 'General business and commerce matters', 'General education matters', 'General energy matters', 
	'General foreign operations matters', 'General health and health care finance matters', 'General public lands matters', 
	'General science and technology matters', 'General taxation matters', 'Genetics', 'Geography and mapping', 
	'Government buildings, facilities, and property', 'Government corporations and government-sponsored enterprises', 
	'Government employee pay, benefits, personnel management', 'Government ethics and transparency, public corruption', 
	'Government information and archives', 'Government lending and loan guarantees', 'Government liability', 
	'Government studies and investigations', 'Government trust funds', 'Grain', 'HIV/AIDS', 'Hate crimes', 
	'Hazardous wastes and toxic substances', 'Health care costs and insurance', 'Health care coverage and access', 
	'Health care quality', 'Health facilities and institutions', 'Health information and medical records', 'Health personnel', 
	'Health programs administration and funding', 'Health promotion and preventive care', 'Health technology, devices, supplies', 
	'Hearing, speech, and vision care', 'Hereditary and development disorders', 'Higher education', 
	'Historic sites and heritage areas', 'Historical and cultural resources', 'Home and outpatient care', 'Homeland security', 
	'Homelessness and emergency shelter', 'Horticulture and plants', 'Hospital care', 'House of Representatives', 
	'Housing and community development funding', 'Housing discrimination', 'Housing finance and home ownership', 
	'Housing for the elderly and disabled', 'Housing industry and standards', 'Housing supply and affordability', 'Human rights', 
	'Human trafficking', 'Humanities programs funding', 'Hunting and fishing', 'Hybrid, electric, and advanced technology vehicles', 
	'Hydrology and hydrography', 'Immigrant health and welfare', 'Immigration status and procedures', 'Immunology and vaccination', 
	'Income tax credits', 'Income tax deductions', 'Income tax deferral', 'Income tax exclusion', 'Income tax rates', 'Indian claims', 
	'Indian lands and resources rights', 'Indian social and development programs', 'Industrial facilities', 
	'Industrial policy and productivity', 'Infectious and parasitic diseases', 'Inflation and prices', 'Infrastructure development', 
	'Insects', 'Insurance industry and regulation', 'Intellectual property', 
	'Intelligence activities, surveillance, classified information', 'Interest, dividends, interest rates', 
	'Intergovernmental relations', 'International exchange and broadcasting', 'International law and treaties', 
	'International monetary system and foreign exchange', 'International organizations and cooperation', 
	'International scientific cooperation', 'Internet, web applications, social media', 'Judges', 
	'Judicial procedure and administration', 'Judicial review and appeals', 'Jurisdiction and venue', 
	'Juvenile crime and gang violence', 'Labor market', 'Labor standards', 'Labor-management relations', 'Lakes and rivers', 
	'Land transfers', 'Land use and conservation', 'Landlord and tenant', 'Language arts', 
	'Law enforcement administration and funding', 'Law enforcement officers', 'Lawyers and legal services', 
	'Lease and rental services', 'Legal fees and court costs', 'Legislative rules and procedure', 'Libraries and archives', 
	'Licensing and registrations', 'Life, casualty, property insurance', 'Lighting, heating, cooling', 'Literature', 'Livestock', 
	'Long-term, rehabilitative, and terminal care', 'Low- and moderate-income housing', 'Mammals', 'Manufacturing', 
	'Marine and coastal resources, fisheries', 'Marine and inland water transportation', 'Marine pollution', 
	'Marketing and advertising', 'Marriage and family status', 'Materials', 'Meat', 'Medicaid', 'Medical education', 'Medical ethics', 
	'Medical research', 'Medical tests and diagnostic methods', 'Medicare', 'Members of Congress', 'Mental health', 'Metals', 
	'Migrant, seasonal, agricultural labor', 'Military assistance, sales, and agreements', 'Military civil functions', 
	'Military command and structure', 'Military education and training', 'Military facilities and property', 'Military history', 
	'Military law', 'Military medicine', 'Military operations and strategy', 'Military personnel and dependents',
    'Military procurement, research, weapons development', 'Military readiness', 'Militias and paramilitary groups', 'Mining', 
	'Minority and disadvantaged businesses', 'Minority education', 'Minority employment', 'Minority health', 'Missing persons', 
	'Monetary policy', 'Monuments and memorials', 'Motor carriers', 'Motor fuels', 'Motor vehicles', 
	'Multilateral development programs', 'Musculoskeletal and skin diseases', 'Museums, exhibitions, cultural centers', 'Music', 
	'National Guard and reserves', 'National and community service', 'National symbols', 'Natural disasters', 
	'Navigation, waterways, harbors', 'Neurological disorders', 'News media and reporting', 'Noise pollution', 
	'Normal trade relations, most-favored-nation treatment', 'Nuclear power', 'Nuclear weapons', 'Nursing', 'Nutrition and diet', 
	'Oil and gas', 'Olympic games', 'Organ and tissue donation and transplantation', 'Organized crime', 'Outdoor recreation', 
	'Palestinians', 'Parks, recreation areas, trails', 'Pedestrians and bicycling', 'Performance measurement', 'Performing arts', 
	'Personnel records', 'Pest management', 'Photography and imaging', 'Physical fitness and lifestyle', 'Pipelines', 'Policy sciences', 
	'Political advertising', 'Political movements and philosophies', 'Political parties and affiliation', 'Political representation', 
	'Pollution liability', 'Pornography', 'Postal service', 'Poverty and welfare assistance', 'Preschool education', 
	'Prescription drugs', 'Presidential administrations', 'Presidents and presidential powers, Vice Presidents', 'Private Legislation', 
	'Product development and innovation', 'Product safety and quality', 'Professional sports', 'Property rights', 'Property tax', 
	'Protection of officials', 'Protest and dissent', 'Public contracts and procurement', 'Public housing', 
	'Public participation and lobbying', 'Public transit', 'Public utilities and utility rates', 'Public-private cooperation', 
	'Racial and ethnic relations', 'Radiation', 'Radio spectrum allocation', 'Radioactive wastes and releases', 'Railroads', 
	'Real estate business', 'Reconstruction and stabilization', 'Refugees, asylum, displaced persons', 
	'Regional and metropolitan planning', 'Religion', 'Reptiles', 'Research administration and funding', 'Research and development', 
	'Research ethics', 'Residential rehabilitation and home repair', 'Retail and wholesale trades', 'Right of privacy', 
	'Roads and highways', 'Rule of law and government transparency', 'Rural conditions and development', 'Sales and excise taxes', 
	'Sanctions', 'School administration', 'School athletics', 'Science and engineering education', 'Scientific communication', 
	'Seafood', 'Seashores and lakeshores', 'Securities', 'Self-employed', 'Senate', 'Separation, divorce, custody, support', 
	'Service animals', 'Service industries', 'Sex and reproductive health', 'Sex offenses', 
	'Sex, gender, sexual orientation discrimination', 'Sexually transmitted diseases', 'Small business', 'Small towns', 
	'Smuggling and trafficking', 'Social security and elderly assistance', 'Social work, volunteer service, charitable organizations', 
	'Soil pollution', 'Solid waste and recycling', 'Sound recording', 'Sovereignty, recognition, national governance and status', 
	'Space flight and exploration', 'Spacecraft and satellites', 'Special education', 'Specialized courts', 
	'Sports and recreation facilities', 'State and local courts', 'State and local finance', 'State and local government operations', 
	'State and local taxation', 'Strategic materials and reserves', 'Student aid and college costs', 'Student records', 
	'Subversive activities', 'Supreme Court', 'Surgery and anesthesia', 'Tariffs', 'Tax administration and collection, taxpayers', 
	'Tax reform and tax simplification', 'Tax treatment of families', 'Tax-exempt organizations', 'Taxation of foreign income', 
	'Teaching, teachers, curricula', 'Technology assessment', 'Technology transfer and commercialization', 'Teenage pregnancy', 
	'Telecommunication rates and fees', 'Telephone and wireless communication', 'Television and film', 
	'Temporary and part-time employment', 'Terrorism', 'Time and calendar', 'Trade adjustment assistance', 
	'Trade agreements and negotiations', 'Trade restrictions', 'Trade secrets and economic espionage', 
	'Transfer and inheritance taxes', 'Transportation costs', 'Transportation employees', 'Transportation programs funding', 
	'Transportation safety and security', 'Travel and tourism', 'U.S. Capitol', 'U.S. and foreign investments', 'U.S. history', 
	'U.S. territories and protectorates', 'Unemployment', 'Urban and suburban affairs and development', 'User charges and fees', 
	"Veterans' education, employment, rehabilitation", "Veterans' loans, housing, homeless programs", "Veterans' medical care", 
	"Veterans' organizations and recognition", "Veterans' pensions and compensation", 'Veterinary medicine and animal diseases',
    'Violent crime', 'Visas and passports', 'Vocational and technical education', 'Voting rights', 'Wages and earnings', 
	'War and emergency powers', 'War crimes, genocide, crimes against humanity', 'Water quality', 'Water resources funding', 
	'Water storage', 'Water use and supply', 'Watersheds', 'Wetlands', 'White-collar crime', 
	'Wilderness and natural areas, wildlife refuges, wild rivers, habitats', 'Wildlife conservation and habitat protection', 
	'Women in business', "Women's education", "Women's employment", "Women's health", "Women's rights", 'Worker safety and health', 
	'World health', 'World history', 'Youth employment and child labor', 'question_On Agreeing to the Conference Report', 
	'question_On Agreeing to the Resolution', 'question_On Agreeing to the Resolution, as Amended', 
	'question_On Cloture on the Motion to Proceed', 'question_On Motion to Concur in the Senate Amendment', 
	'question_On Motion to Recommit', 'question_On Motion to Recommit with Instructions', 'question_On Motion to Refer', 
	'question_On Motion to Suspend the Rules and Agree', 'question_On Motion to Suspend the Rules and Agree, as Amended', 
	'question_On Motion to Suspend the Rules and Concur in the Senate Amendment', 
	'question_On Motion to Suspend the Rules and Pass', 'question_On Motion to Suspend the Rules and Pass, as Amended', 
	'question_On Motion to Table', 'question_On Ordering the Previous Question', 'question_On Overriding the Veto', 
	'question_On Passage', 'question_On Passage of the Bill', 'question_On the Cloture Motion', 
	'question_On the Joint Resolution', 'question_On the Motion', 'question_On the Motion to Discharge', 
	'question_On the Motion to Proceed', 'question_On the Resolution', 
	'question_Passage, Objections of the President To The Contrary Notwithstanding', 'question_Table Motion to Reconsider']

def modifyCountyGeoJSON(congress_id):
    read_url = 'BillQuery/static/geojsons/cb_us_cd' + str(congress_id) + '_5m.geojson'
    write_url = 'BillQuery/static/geojsons/cb_us_cd' + str(congress_id) + '_5m.geojson'
    modify(read_url, write_url)

def modifyStateGeoJSON():
    read_url = 'BillQuery/static/geojsons/cb_us_state_5m.geojson'
    write_url = 'BillQuery/static/geojsons/cb_us_state_5m.geojson'
    modify(read_url, write_url)

def modify(read_url, write_url):
    with open(read_url) as json_file:
        data = json.load(json_file)
        for i in range(len(data['features'])) : 
            data['features'][i]['id'] = data['features'][i]['properties']['GEOID']
        with open(write_url, 'w') as write_file:
            json.dump(data, write_file, indent=1)

async def predictVote(bill_id, membership, question):
    header_str = '&api_key=' + settings.CONGRESS_KEY + '&format=json&limit=250'
    session = aiohttp.ClientSession()
    v_session = aiohttp.ClientSession()
    pattern = re.compile(r'\s{2,}')
    model = "gemini-2.0-flash"
    client = genai.Client(api_key = settings.GEMINI_KEY)
    generate_content_config = types.GenerateContentConfig(response_mime_type="text/plain")

    # gets text versions of 
    mult = 1 if bill_id < 99999999 else 10
    congress_num = bill_id //(100000 * mult)
    type_enum = bill_id // (10000 * mult) % 10
    _type = utils.types[type_enum]
    bill_num = bill_id % (10000 * mult)
    full_path = settings.CONGRESS_DIR + 'bill/' + str(congress_num) + '/' + _type + '/' + str(bill_num)
    texts = await utils.connectASYNC(session, full_path + '/text?', header_str)
    subjects = await utils.connectASYNC(session, full_path + '/subjects?', header_str)
    if not subjects:
        print('SUBJECT LIST EMPTY')
        return
    subject_literal = '['
    for subject in subjects['subjects']['legislativeSubjects']:
        subject_literal += '"' + subject['name'] + '",'
    subject += ']'
    indx = -1
    latest_date = datetime.datetime(1,1,1,1,1,1)
    for j in range(len(texts['textVersions'])):
        date_str = texts['textVersions'][j]['date']
        if date_str == None: continue
        curr_date = datetime.datetime(
            int(date_str[0:4]),
            int(date_str[5:7]),
            int(date_str[8:10]),
            int(date_str[11:13]),
            int(date_str[14:16]),
            int(date_str[17:19]),
            )
        if (curr_date > latest_date):
            latest_date = curr_date
            indx = j
    if indx == -1:
        print('NO TEXT DATA AVAILABLE')
        return 
    txt_html = await utils.connectASYNC(v_session, texts['textVersions'][indx]['formats'][0]['url'],'',False)
    if txt_html == None:
        print('MISSING TEXT ERROR')
        return
    soup = BeautifulSoup(txt_html)
    version_text = soup.get_text()
    version_text = version_text.replace('\n','').replace('_','')
    version_text = re.sup(pattern,'').replace('_','')
    ctns = [version_text, subject_literal, prompt]
    token_count = client.models.count_tokens(model = model, contents = ctns)
    if token_count.total_tokens > 1000000:
        print("INPUT TOO BIG")
        return
    response = await client.aio.models.generate_content(
        model = model,
        contents = ctns,
        config = generate_content_config)
    response = response.text
    response = response.removeprefix("```python")
    response = response.removesuffix("```")
    response = response.removesuffix("```\n")
    try:
        d = ast.literal_eval(response)
    except:
        print("ERROR MAKING LITERAL", response)
    model = tf.keras.models.load_model('models/model.keras')
    df =pd.DataFrame({c: pd.Series(dtype='int64') for c in feature_list})
    df.loc[0] = 0
	# add member data
    df.loc[0, 'house'] = 1 if membership.house else 0
    df.loc[0, 'party_' + membership.party] = 1
	# add bill features
    for key in list(d.keys()):
        if key in subject_dict:
            df.loc[0, key] = d[key]

	# add question point
    df.loc[0, 'question_' + question] = 1
    fit = model.predict(df)
	




