# Generated by Django 4.2.7 on 2024-11-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('congress_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('image_link', models.CharField(blank=True, max_length=150, null=True)),
                ('api_url', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=40, null=True)),
                ('facebook', models.CharField(blank=True, max_length=40, null=True)),
                ('youtube', models.CharField(blank=True, max_length=40, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('votesmart_id', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_num', models.IntegerField(blank=True, null=True)),
                ('chamber', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('party', models.CharField(max_length=30)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10, null=True)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.congress')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenateQuery.member')),
            ],
        ),
        migrations.AddField(
            model_name='congress',
            name='members',
            field=models.ManyToManyField(related_name='members_set', through='SenateQuery.Membership', to='SenateQuery.member'),
        ),
    ]
