# Generated by Django 4.2.7 on 2024-12-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='votesmart_id',
        ),
        migrations.AddField(
            model_name='member',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='death_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='official_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='leadership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
