# Generated by Django 4.2.7 on 2024-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0002_remove_member_votesmart_id_member_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
