# Generated by Django 4.2.7 on 2024-12-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0003_member_first_name_member_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='death_year',
        ),
    ]
