# Generated by Django 4.2.7 on 2024-12-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0004_remove_member_death_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='death_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
