# Generated by Django 4.2.7 on 2025-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0005_member_death_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(max_length=14),
        ),
    ]
