# Generated by Django 4.2.7 on 2025-02-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0006_congress_end_year_congress_start_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congress',
            options={'ordering': ['-congress_num']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['state', 'member__full_name']},
        ),
    ]
