# Generated by Django 4.2.7 on 2025-02-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0008_remove_membership_leadership_membership_geoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='chamber',
        ),
        migrations.AddField(
            model_name='membership',
            name='house',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='geoid',
            field=models.CharField(max_length=4),
        ),
    ]
