# Generated by Django 4.2.7 on 2025-02-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0009_remove_member_api_url_remove_membership_chamber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
