# Generated by Django 4.2.20 on 2025-04-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenateQuery', '0010_alter_membership_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
