# Generated by Django 5.2.9 on 2026-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_resend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
