# Generated by Django 5.2.9 on 2026-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emailverification_last_resend_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
