# Generated by Django 5.2.10 on 2026-01-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_user_type_favoritesubjects_starredmember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='starredmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='starredmember',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='FavoriteSubjects',
        ),
        migrations.DeleteModel(
            name='StarredMember',
        ),
    ]
