# Generated by Django 5.2.10 on 2026-02-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_starredmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scheduled_for_deletion',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
