# Generated by Django 5.2.10 on 2026-03-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_scheduled_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enabled_bill_notif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enabled_subject_notif',
            field=models.BooleanField(default=True),
        ),
    ]
