# Generated by Django 5.2.10 on 2026-04-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_enabled_bill_notif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('apple', 'Apple')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauth_provider_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
