# Generated by Django 5.2.10 on 2026-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile_oauth_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('apple', 'Apple')], max_length=10, null=True),
        ),
    ]
